export enum Command_ID {
  FORCE_REBOOT = 0x40,
  SWITCH_TO_STATE = 0x41,
  UPLINK_TIME_REFERENCE = 0x42,
  UPLINK_ORBIT_REFERENCE = 0x43,
  TURN_OFF_PAYLOAD = 0x44,
  SCHEDULE_OD_EXPERIMENT = 0x45,

  REQUEST_TM_HEARTBEAT = 0x46,
  REQUEST_TM_HAL = 0x47,
  REQUEST_TM_STORAGE = 0x48,
  REQUEST_TM_PAYLOAD = 0x49,

  REQUEST_FILE_METADATA = 0x4a,
  REQUEST_FILE_PKT = 0x4b,
  REQUEST_IMAGE = 0x4c,
}
