{
 "title": "EPS - Summary",
 "tags": [
  "satellite",
  "EPS",
  "power"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Battery State of Charge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_REPORTED_SOC\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_VOLTAGE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_CURRENT\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Mainboard Temperature (°C)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_TEMPERATURE\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 }))"
    }
   ]
  },
  {
   "title": "Battery Voltage History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_VOLTAGE\")"
    }
   ]
  },
  {
   "title": "Battery Current History (+ = Charging, - = Discharging)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_CURRENT\")"
    }
   ]
  },
  {
   "title": "Solar Panel Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /SOLAR_CHARGE_VOLTAGE/)"
    }
   ]
  },
  {
   "title": "Solar Panel Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /SOLAR_CHARGE_CURRENT/)"
    }
   ]
  },
  {
   "title": "System Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RF_LDO_OUTPUT_VOLTAGE\" or r[\"_field\"] == \"GPS_VOLTAGE\" or r[\"_field\"] == \"MAINBOARD_VOLTAGE\")"
    }
   ]
  },
  {
   "title": "System Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RF_LDO_OUTPUT_CURRENT\" or r[\"_field\"] == \"GPS_CURRENT\" or r[\"_field\"] == \"MAINBOARD_CURRENT\")"
    }
   ]
  }
 ]
}